# Generated by Django 5.2.17 on 2026-09-25 16:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def install_controls(apps, schema_editor):
    schema_editor.execute("""
    DO $$ BEGIN
      IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'wealth_app') THEN
        GRANT SELECT, INSERT, UPDATE, DELETE ON wealth_platformsetting, wealth_navigationpreference, wealth_platformuserstate, wealth_platformcommand TO wealth_app;
        GRANT SELECT, INSERT ON wealth_platformaudit TO wealth_app;
        GRANT USAGE, SELECT ON SEQUENCE wealth_platformcommand_id_seq TO wealth_app;
      END IF;
    END $$;
    CREATE TRIGGER immutable_platform_audit BEFORE UPDATE OR DELETE ON wealth_platformaudit
    FOR EACH ROW EXECUTE FUNCTION wealth_no_fact_mutation();
    """)


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("wealth", "0007_market_symbol"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NavigationPreference",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("groups", models.JSONField(default=dict)),
                ("version", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="PlatformSetting",
            fields=[
                (
                    "key",
                    models.CharField(max_length=80, primary_key=True, serialize=False),
                ),
                ("data", models.JSONField(default=dict)),
                ("version", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="PlatformUserState",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="PlatformAudit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("action", models.CharField(max_length=100)),
                ("target", models.CharField(blank=True, max_length=160)),
                ("detail", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlatformCommand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("command", models.CharField(max_length=180)),
                ("key", models.CharField(max_length=160)),
                ("digest", models.CharField(max_length=64)),
                ("result", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("actor", "command", "key"),
                        name="platform_command_identity",
                    )
                ],
            },
        ),
        migrations.RunPython(install_controls, migrations.RunPython.noop),
    ]
