# Generated by Django 5.2.17 on 2026-09-27 13:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def install_cleanup_functions(apps, schema_editor):
    tenant_tables = [
        model._meta.db_table
        for model in apps.get_app_config("wealth").get_models()
        if any(field.name == "tenant" for field in model._meta.fields)
    ]
    updates = "\n".join(
        f"UPDATE public.{table} SET created_by_id = NULL WHERE tenant_id = sid AND created_by_id = victim;"
        for table in tenant_tables
    )
    deletes = "\n".join(
        f"DELETE FROM public.{table} WHERE tenant_id = wanted;"
        for table in tenant_tables
    )
    schema_editor.execute("""
    CREATE TABLE public.wealth_cleanup_scope (
      backend_pid integer NOT NULL,
      transaction_id bigint NOT NULL,
      workspace_id uuid,
      target_user_id bigint,
      PRIMARY KEY (backend_pid, transaction_id)
    );
    REVOKE ALL ON public.wealth_cleanup_scope FROM PUBLIC;
    DO $$ BEGIN
      IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'wealth_app') THEN
        REVOKE ALL ON public.wealth_cleanup_scope FROM wealth_app;
      END IF;
    END $$;
    CREATE FUNCTION public.wealth_cleanup_permitted(wanted_space uuid, wanted_user bigint)
    RETURNS boolean LANGUAGE sql SECURITY DEFINER SET search_path = pg_catalog, public AS $$
      SELECT EXISTS (
        SELECT 1 FROM public.wealth_cleanup_scope
        WHERE backend_pid = pg_backend_pid() AND transaction_id = txid_current()
          AND (wanted_space IS NOT NULL AND workspace_id = wanted_space
               OR wanted_user IS NOT NULL AND target_user_id = wanted_user)
      );
    $$;
    CREATE OR REPLACE FUNCTION public.wealth_no_fact_mutation() RETURNS trigger
    LANGUAGE plpgsql AS $$
    DECLARE old_row jsonb; new_row jsonb;
    BEGIN
      old_row := to_jsonb(OLD);
      IF TG_OP = 'DELETE' AND old_row ? 'tenant_id'
         AND public.wealth_cleanup_permitted((old_row->>'tenant_id')::uuid, NULL) THEN
        RETURN OLD;
      END IF;
      IF TG_OP = 'UPDATE' THEN
        new_row := to_jsonb(NEW);
        IF old_row ? 'created_by_id' AND new_row->>'created_by_id' IS NULL
           AND new_row - 'created_by_id' = old_row - 'created_by_id'
           AND public.wealth_cleanup_permitted(NULL, (old_row->>'created_by_id')::bigint) THEN
          RETURN NEW;
        END IF;
        IF TG_TABLE_NAME = 'wealth_platformaudit' AND new_row->>'actor_id' IS NULL
           AND (new_row->>'actor_reference')::bigint = (old_row->>'actor_id')::bigint
           AND new_row - ARRAY['actor_id','actor_label','actor_reference'] = old_row - ARRAY['actor_id','actor_label','actor_reference']
           AND public.wealth_cleanup_permitted(NULL, (old_row->>'actor_id')::bigint) THEN
          RETURN NEW;
        END IF;
      END IF;
      RAISE EXCEPTION 'Posted financial facts are immutable; reverse and replace' USING ERRCODE='23514';
    END; $$;
    """)
    schema_editor.execute(
        """
    CREATE FUNCTION public.wealth_purge_workspace(operator bigint, wanted uuid, expected bigint, confirmation text)
    RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path = pg_catalog, public AS $$
    DECLARE old_scope text; current_space public.wealth_workspace%%ROWTYPE;
    BEGIN
      PERFORM pg_advisory_xact_lock(812339402);
      IF NOT EXISTS (SELECT 1 FROM public.auth_user WHERE id=operator AND is_active AND is_superuser) THEN
        RAISE EXCEPTION 'Active platform administrator required' USING ERRCODE='42501';
      END IF;
      SELECT * INTO current_space FROM public.wealth_workspace WHERE id=wanted FOR UPDATE;
      IF current_space.id IS NULL OR current_space.deleted_at IS NULL
         OR current_space.revision <> expected OR current_space.name <> confirmation THEN
        RAISE EXCEPTION 'Deleted workspace, current version and exact name required' USING ERRCODE='23514';
      END IF;
      old_scope := COALESCE(current_setting('app.tenant_id', true), '');
      PERFORM set_config('app.tenant_id', wanted::text, true);
      -- Validate previously queued facts before removing their whole workspace.
      SET CONSTRAINTS ALL IMMEDIATE;
      SET CONSTRAINTS ALL DEFERRED;
      INSERT INTO public.wealth_cleanup_scope VALUES (pg_backend_pid(), txid_current(), wanted, NULL);
    """
        + deletes
        + """
      UPDATE public.wealth_configurationtemplate SET source_workspace_id=NULL WHERE source_workspace_id=wanted;
      DELETE FROM public.wealth_membership WHERE workspace_id=wanted;
      DELETE FROM public.wealth_workspace WHERE id=wanted;
      DELETE FROM public.wealth_cleanup_scope WHERE backend_pid=pg_backend_pid() AND transaction_id=txid_current();
      PERFORM set_config('app.tenant_id', old_scope, true);
    END; $$;
    CREATE FUNCTION public.wealth_delete_platform_user(operator bigint, victim bigint, expected bigint, confirmation text)
    RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path = pg_catalog, public AS $$
    DECLARE old_scope text; sid uuid; victim_name text; victim_admin boolean; victim_active boolean;
    BEGIN
      PERFORM pg_advisory_xact_lock(812339402);
      IF operator = victim OR NOT EXISTS (SELECT 1 FROM public.auth_user WHERE id=operator AND is_active AND is_superuser) THEN
        RAISE EXCEPTION 'Another active platform administrator required' USING ERRCODE='42501';
      END IF;
      SELECT username,is_superuser,is_active INTO victim_name,victim_admin,victim_active
        FROM public.auth_user WHERE id=victim FOR UPDATE;
      IF victim_name IS NULL OR victim_name <> confirmation
        OR COALESCE((SELECT version FROM public.wealth_platformuserstate WHERE user_id=victim),0) <> expected THEN
        RAISE EXCEPTION 'Existing user, current version and exact username required' USING ERRCODE='23514';
      END IF;
      IF victim_admin AND victim_active AND NOT EXISTS (
        SELECT 1 FROM public.auth_user WHERE id<>victim AND is_active AND is_superuser
      ) THEN RAISE EXCEPTION 'The last active administrator cannot be deleted' USING ERRCODE='23514'; END IF;
      IF EXISTS (
        SELECT 1 FROM public.wealth_membership member JOIN public.wealth_workspace space ON space.id=member.workspace_id
        WHERE member.user_id=victim AND member.role='owner' AND space.deleted_at IS NULL
          AND NOT EXISTS (SELECT 1 FROM public.wealth_membership replacement JOIN public.auth_user person ON person.id=replacement.user_id
            WHERE replacement.workspace_id=member.workspace_id AND replacement.role='owner' AND replacement.user_id<>victim
              AND person.is_active AND NOT person.is_superuser)
      ) THEN RAISE EXCEPTION 'Transfer active workspace ownership first' USING ERRCODE='23514'; END IF;
      old_scope := COALESCE(current_setting('app.tenant_id', true), '');
      INSERT INTO public.wealth_cleanup_scope VALUES (pg_backend_pid(), txid_current(), NULL, victim);
      FOR sid IN SELECT id FROM public.wealth_workspace ORDER BY id FOR UPDATE LOOP
        PERFORM set_config('app.tenant_id', sid::text, true);
        DELETE FROM public.wealth_idempotency WHERE tenant_id=sid AND actor_id=victim;
    """
        + updates
        + """
      END LOOP;
      UPDATE public.wealth_configurationtemplate SET source_user_id=NULL WHERE source_user_id=victim;
      UPDATE public.wealth_configurationtemplate SET created_by_id=NULL WHERE created_by_id=victim;
      UPDATE public.wealth_platformaudit SET actor_id=NULL, actor_reference=victim,
        actor_label=CASE WHEN actor_label='' THEN victim_name ELSE actor_label END WHERE actor_id=victim;
      DELETE FROM public.wealth_platformcommand WHERE actor_id=victim;
      DELETE FROM public.wealth_navigationpreference WHERE user_id=victim;
      DELETE FROM public.wealth_platformuserstate WHERE user_id=victim;
      DELETE FROM public.wealth_membership WHERE user_id=victim;
      DELETE FROM public.auth_user_groups WHERE user_id=victim;
      DELETE FROM public.auth_user_user_permissions WHERE user_id=victim;
      DELETE FROM public.auth_user WHERE id=victim;
      DELETE FROM public.wealth_cleanup_scope WHERE backend_pid=pg_backend_pid() AND transaction_id=txid_current();
      PERFORM set_config('app.tenant_id', old_scope, true);
    END; $$;
    REVOKE ALL ON FUNCTION public.wealth_purge_workspace(bigint,uuid,bigint,text) FROM PUBLIC;
    REVOKE ALL ON FUNCTION public.wealth_delete_platform_user(bigint,bigint,bigint,text) FROM PUBLIC;
    REVOKE ALL ON FUNCTION public.wealth_cleanup_permitted(uuid,bigint) FROM PUBLIC;
    DO $$ BEGIN
      IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname='wealth_app') THEN
        GRANT EXECUTE ON FUNCTION public.wealth_purge_workspace(bigint,uuid,bigint,text) TO wealth_app;
        GRANT EXECUTE ON FUNCTION public.wealth_delete_platform_user(bigint,bigint,bigint,text) TO wealth_app;
        GRANT EXECUTE ON FUNCTION public.wealth_cleanup_permitted(uuid,bigint) TO wealth_app;
      END IF;
    END $$;
    """
    )


class Migration(migrations.Migration):
    dependencies = [
        ("wealth", "0009_workspace_management_templates"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="platformaudit",
            name="actor_label",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="platformaudit",
            name="actor_reference",
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="configurationtemplate",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="configurationtemplate",
            name="source_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="configurationtemplate",
            name="source_workspace",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="wealth.workspace",
            ),
        ),
        migrations.AlterField(
            model_name="platformaudit",
            name="actor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(install_cleanup_functions, migrations.RunPython.noop),
    ]
